### ISSUE TITLE
Change extension for generated files for Coveralls

### ISSUE THREAD

**Issue by adamhathcock** [daver32/InterfaceGenerator#14]
Basically, could the extension be `.g.cs` instead of just `.cs` which seems to be some convention for source generated files.

Coveralls will exclude these as well.  I can't get any work around manually to exclude them to work.

https://github.com/coverlet-coverage/coverlet/issues/1084

Thanks!

**Comment by onsatoci** [comment]
Thanks for the PR, merged and included in v1.0.14
