### ISSUE TITLE
Feature Request: Init only setters

### ISSUE THREAD

**Issue by andi0b** [daver32/InterfaceGenerator#2]
This library seems not to support [init only setters from c# 9](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init)

## how to reproduce
Tested on 1.0.5 on net6.0

Given this code:
```csharp
[InterfaceGenerator.GenerateAutoInterface]
class Class : IClass
{
    public string Property { get; init; }
}
```

AutoInterface creates this interface:
```csharp
internal partial interface IClass
{
    string Property { get; set; }
}
```

but it should be:
```csharp
internal partial interface IClass
{
    string Property { get; init; }
}
```

**Comment by onsatoci** [comment]
I've added support for that now, check out the newest version
